<br>
<div class="panel panel-default">
	<div class="panel-heading">
<?php
if ($action == 'ship') $title = 'Envoi ASNLIV'; 
elseif ($action == 'deliver') $title = 'Envoi ASNLIV1'; 
elseif ($action == 'commission') $title = 'Envoi ASNLIV2'; 
?>
		<strong><?php echo $this->translate($title, 'ppit-order', $context->getLocale()) ?></strong>
<!-- 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php //echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="<?php //echo 'update-remove-anchor-'.$order->id ?>">
				<span class="glyphicon glyphicon-remove" id="<?php //echo 'remove-anchor-'.$order->id ?>-glyphicon"></span>
			</button>
		</div> -->
	</div>
	<div class="panel-body">

		<!-- Form header -->
		<?php echo $this->partial('/partials/form-header', array(
					'update_time' => $order->update_time,
					'message' => $message,
					'error' => $error,
					'csrfForm' => $csrfForm,
					'context' => $context,
		));
		?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
		
		<!-- Equipment identifier -->
		<div class="form-group" id="equipment_identifier_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Numéro de série', 'ppit-order', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="equipment_identifier" id="equipment_identifier" class="form-control" value="<?php echo $order->uniqueOrderProduct->equipment_identifier ?>"<?php if ($order->uniqueOrderProduct->equipment_identifier || isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="equipment_identifier_error"></p></div>
		</div>
		
		<!-- Changed equipment identifier -->
		<div class="form-group" id="changed_equipment_identifier_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Numéro de série modifié', 'ppit-order', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input name="changed_equipment_identifier" id="changed_equipment_identifier" class="form-control" value="<?php echo $order->uniqueOrderProduct->changed_equipment_identifier ?>"<?php if (!$order->uniqueOrderProduct->equipment_identifier || $order->uniqueOrderProduct->changed_equipment_identifier || isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="changed_equipment_identifier_error"></p></div>
		</div>

<?php if ($action == 'ship') : ?>

<!--  Ship -->
		
		<!-- Shipment date-->
		<div class="form-group" id="input_shipment_date_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Date de départ Venray', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" name="shipment_date" id="shipment_date" />
				<input id="input_shipment_date" name="input_shipment_date" class="form-control" value="<?php echo $orderProduct->shipment_date ?>" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled="disabled"' ?>/>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_shipment_date_error"></p></div>
		</div>
		
		<!-- Comment -->
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Commentaire (interne Xerox)', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea name="comment" id="comment" rows="3" class="form-control"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>

		<!-- Price (hidden) -->
		<input type="hidden" id="price" name="price" value="<?php echo $orderProduct->price?>" />

		<!-- Hopped delivery date -->
		<input type="hidden" id="hoped_delivery_date" name="hoped_delivery_date" value="<?php echo $orderProduct->hoped_delivery_date?>" />
		
<?php elseif ($action == 'deliver') : ?>

<!--  Deliver -->

		<!-- Delivery date-->
		<div class="form-group" id="input_delivery_date_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Date de livraison réelle', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" name="delivery_date" id="delivery_date" />
				<input id="input_delivery_date" name="input_delivery_date" class="form-control" value="<?php echo $orderProduct->delivery_date ?>" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>/>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_delivery_date_error"></p></div>
		</div>
		
		<!-- Comment -->
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Commentaire (interne Xerox)', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea name="comment" id="comment" rows="3" class="form-control"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>
		
		<!-- Price (hidden) -->
		<input type="hidden" id="price" name="price" value="<?php echo $orderProduct->price?>" />

		<!-- Hopped delivery date -->
		<input type="hidden" id="hoped_delivery_date" name="hoped_delivery_date" value="<?php echo $orderProduct->hoped_delivery_date?>" />

		<!-- Shipment date -->
		<input type="hidden" id="shipment_date" name="shipment_date" value="<?php echo $orderProduct->shipment_date?>" />

<?php elseif ($action == 'commission') : ?>

<!--  Commission -->

		<!-- Commissioning date-->
		<div class="form-group" id="input_commissioning_date_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Date de mise en service', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" name="commissioning_date" id="commissioning_date" />
				<input id="input_commissioning_date" name="input_commissioning_date" class="form-control" value="<?php echo $orderProduct->commissioning_date ?>" <?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>/>
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_commissioning_date_error"></p></div>
		</div>
		
		<!-- Comment -->
		<div class="form-group" id="comment_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Commentaire (interne Xerox)', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<textarea name="comment" id="comment" rows="3" class="form-control"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>></textarea>
			</div>
			<div class="col-sm-12"><p class="help-block" id="comment_error"></p></div>
		</div>
		
		<!-- Price (hidden) -->
		<input type="hidden" id="price" name="price" value="<?php echo $orderProduct->price?>" />
		
		<!-- Equipment identifier (hidden) -->
		<input type="hidden" id="equipment_identifier" name="equipment_identifier" value="<?php echo $orderProduct->equipment_identifier ?>" />
		
		<!-- Hopped delivery date -->
		<input type="hidden" id="hoped_delivery_date" name="hoped_delivery_date" value="<?php echo $orderProduct->hoped_delivery_date?>" />

		<!-- Shipment date -->
		<input type="hidden" id="shipment_date" name="shipment_date" value="<?php echo $orderProduct->shipment_date?>" />

		<!-- Delivery date -->
		<input type="hidden" id="delivery_date" name="delivery_date" value="<?php echo $orderProduct->delivery_date?>" />

<?php endif;?>

<?php if ($message == 'OK') : ?>

<!-- Foot return link -->
<!--			<div class="form-group" id="foot_return_link">
				<div class="col-sm-4">&nbsp;</div>
				<div class="col-sm-8">
					<button type="button" class="btn btn-default" title="<?php //echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="<?php //echo 'update-foot-return-anchor-'.$order->id ?>">
						<span><?php //echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></span>
					</button>
				</div>
			</div> ->

<?php else : ?>

<!-- Submit button -->
		    <div class="form-group">
				<div class="col-sm-4">&nbsp;</div>
				<div class="col-sm-8">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning ?>" value="<?php echo $this->translate('Confirm', 'ppit-core', $context->getLocale()) ?>">
					&nbsp;&nbsp;
					<button type="button" class="btn btn-default" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'update-cancel-anchor-'.$order->id ?>">
						<span><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></span>
					</button>
				</div>
			</div>

<?php endif;?>

		</form>
	</div>
</div>
