<div class="panel panel-default">
	<div class="panel-body">
		<div>
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'remove-anchor' ?>">
				<span class="glyphicon glyphicon-remove" id="<?php echo 'remove-anchor' ?>-glyphicon"></span>
			</button>
		</div>

		<div>&nbsp;</div>

<!-- Display the audit -->
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label-<?php echo $order->id ?>" href="#"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel-<?php echo $order->id ?>" class="panel panel-default">
			<div class="panel-body">
<?php foreach ($incident->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php echo $this->translate($statusDescriptor[$comment['status']]['labels'][$context->getLocale()], 'ppit-core', $context->getLocale()) ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
<?php endforeach;?>
			</div>
		</div>

		<div>&nbsp;</div>

		<div>

<?php foreach ($config['ppitSupportSettings']['incidentActions'] as $actionId => $action) : ?>
	<?php foreach ($action['responsible'] as $role) : ?>
		<?php if ($context->hasRole($role)) : ?>
			<button type="button" class="btn action-btn" id="<?php echo $actionId ?>-anchor-<?php echo $incident->id ?>">
				<span><?php echo $action['label'][$context->getLocale()] ?></span>
			</button>
		<?php endif;?>
	<?php endforeach;?>
<?php endforeach;?>	

		</div>

	<div id="imap-incident-update-panel-<?php echo $incident->id ?>"></div>
